Staking Apy & other minor changes
OriginProtocol/ousd.com pull request #60
Opened 2023-01-24 03:39 UTC by HrikB

Changes included within this PR:
- Routing on header and footer refresh page (on same tab)
- Addresses in circulating supply tooltip link to etherscan
- APY calculation done in `/burn` route has been abstracted for reuse (`useOgv()`). This is then used to wire up the dashboard to the APY

Closes #53 
Closes #54 
Closes #55 
Closes #56 
Closes #57

2023-01-24 04:18 UTC, shahthepro requested changes
A minor concern about numerical operations, otherwise looks good to me

2023-01-24 04:18 UTC, shahthepro commented on src/hooks/useOgv.ts
> +      const supply = await ogv.totalSupply().then((r) => Number(r) / 10 ** 18);
I guess converting BigNumber to Number and then scaling it to 10^18 decimals is gonna cause rounding and other issues since JS's primitive Number type cannot handle larger numbers.

Would be better and cleaner to do the conversion on BigNumber before casting into Number. Also, could just use `ethers.utils.formatUnits` method

2023-01-24 04:18 UTC, shahthepro commented on src/hooks/useOgv.ts
> +    }
nit: I wonder if we need a `loading` or `error` state as well, so that the UI can handle it properly. Not a blocker or big deal though

2023-01-24 17:39 UTC, HrikB commented on src/hooks/useOgv.ts
> +      const supply = await ogv.totalSupply().then((r) => Number(r) / 10 ** 18);
Done!

2023-01-25 09:56 UTC, shahthepro approved these changes
LGTM, Thanks for addressing the comment

2023-01-26 05:31 UTC, merged