refactor strategy allocation
OriginProtocol/ousd.com pull request #80
Opened 2023-02-14 18:37 UTC by rolandpo

refactor strategy allocation with the structured analytics endpoint, replacing #45

requires removing COMP from analytics if possible otherwise can edit just frontend to exclude it

2023-02-15 02:52 UTC, shahthepro requested changes
I still see some parts using the name instead of UUID

2023-02-15 02:52 UTC, shahthepro commented on src/components/Allocation.js
> +                      if (protocol.name == 'undefined' || protocol.name === 'Vault') return
let's not use the name. You can pass the UUID as key or something and use that here

2023-02-15 02:52 UTC, shahthepro commented on src/components/Allocation.js
> +                              [protocol.name]: !open[protocol.name],
Let's use UUID instead of name

2023-02-15 02:52 UTC, shahthepro commented on src/components/Allocation.js
> +                                  src={protocolMapping[protocol.name]?.image}
Same comment here about name usage

2023-02-15 11:14 UTC, rolandpo commented on src/components/Allocation.js
> +                      if (protocol.name == 'undefined' || protocol.name === 'Vault') return
the UUID refers to the strategies as defined in analytics, doesn't it? I need to iterate just through protocols here, so Convex, Morpho, Aave, Compound

2023-02-23 15:08 UTC, sparrowDom approved these changes
LGTM

2023-02-24 10:30 UTC, shahthepro approved these changes

2023-02-24 10:30 UTC, merged